### ISSUE TITLE
homee down - kein Neustart der Instanz

### ISSUE THREAD

**Issue by fisch55** [Apollon77/ioBroker.homee#10]
Sobald homee crasht , abstürzt oder sonst irgendwie nicht erreichbar ist, bleibt die Instanz von homee auf gelb, auch wenn homee seinen Dienst bereits wieder verrichtet.

Ist mir schon mehrmals aufgefallen, dass ich die Instanz dann händisch starten muss.Vielleicht lässt sich hier Abhilfe schaffen .

**Comment by Apollon77** [comment]
Steht etwas hilfreiches im log wenn die instanz offline geht?

**Comment by fisch55** [comment]
mmm, ob das hilfreich ist weiss ich nicht.

`homee connection error: "Error: Opening handshake has timed out"`
`DISCONNECTED: 1006`
`RECONNECT: 17`


homee.0 | 2018-08-17 20:55:15.500 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:55:15.096 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:54:36.918 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:54:36.527 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:54:33.841 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:54:33.725 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:54:28.815 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:54:28.493 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:54:05.265 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:54:04.978 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:42:01.362 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:42:01.331 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:40:35.461 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:40:35.437 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:40:35.387 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:37.478 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:36.988 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:36.936 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:36.892 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:36.860 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:31.590 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:31.563 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:31.492 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:31.008 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:30.972 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:30.933 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:30.872 | info | initialize 1 homeegrams
homee.0 | 2018-08-17 20:25:11.490 | info | initialize 1 nodes
homee.0 | 2018-08-17 20:25:06.577 | info | initialize 1 nodes
homee.0 | 2018-08-17 20:10:48.686 | info | initialize 108 homeegrams
homee.0 | 2018-08-17 20:10:45.415 | info | initialize 107 nodes
homee.0 | 2018-08-17 20:10:44.361 | info | CONNECTED
homee.0 | 2018-08-17 20:10:44.156 | info | Init homee homee.fritz.box for user iobroker
homee.0 | 2018-08-17 20:10:44.115 | info | starting. Version 0.3.1 in /opt/iobroker/node_modules/iobroker.homee, node: v6.14.3
yahka.0 | 2018-08-17 20:10:41.803 | info | objectChange system.adapter.homee.0 {"_id":"system.adapter.homee.0","type":"instance","common":{"name":"homee","version":"0.3.1","news":{"0.1.0":{"en":"initial adapter","de":"Initiale Version","ru":"
host.ioBroker-Pi | 2018-08-17 20:10:41.791 | info | instance system.adapter.homee.0 started with pid 14182
host.ioBroker-Pi | 2018-08-17 20:10:41.693 | info | object change system.adapter.homee.0
host.ioBroker-Pi | 2018-08-17 20:10:40.658 | info | instance system.adapter.homee.0 terminated with code 0 (OK)
yahka.0 | 2018-08-17 20:10:40.609 | info | objectChange system.adapter.homee.0 {"_id":"system.adapter.homee.0","type":"instance","common":{"name":"homee","version":"0.3.1","news":{"0.1.0":{"en":"initial adapter","de":"Initiale Version","ru":"
homee.0 | 2018-08-17 20:10:40.598 | info | terminating
host.ioBroker-Pi | 2018-08-17 20:10:40.554 | info | stopInstance system.adapter.homee.0 killing pid 13535
host.ioBroker-Pi | 2018-08-17 20:10:40.553 | info | stopInstance system.adapter.homee.0
host.ioBroker-Pi | 2018-08-17 20:10:40.547 | info | "system.adapter.homee.0" disabled
homee.0 | 2018-08-17 20:10:40.561 | info | cleaned everything up...
host.ioBroker-Pi | 2018-08-17 20:10:40.545 | info | object change system.adapter.homee.0
homee.0 | 2018-08-17 15:58:37.079 | info | Init homee homee.fritz.box for user xxx
homee.0 | 2018-08-17 15:58:37.035 | info | starting. Version 0.3.1 in /opt/iobroker/node_modules/iobroker.homee, node: v6.14.3
host.ioBroker-Pi | 2018-08-17 15:58:34.291 | info | instance system.adapter.homee.0 started with pid 13535
host.ioBroker-Pi | 2018-08-17 15:58:04.208 | info | Restart adapter system.adapter.homee.0 because enabled
host.ioBroker-Pi | 2018-08-17 15:58:04.208 | error | instance system.adapter.homee.0 terminated with code 0 (OK)
Caught | 2018-08-17 15:58:04.199 | error | by controller[0]: at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.homee/main.js:127:11)
Caught | 2018-08-17 15:58:04.198 | error | by controller[0]: at Homee.setValue (/opt/iobroker/node_modules/iobroker.homee/node_modules/homee-api/homee.js:274:14)
Caught | 2018-08-17 15:58:04.196 | error | by controller[0]: at Homee.send (/opt/iobroker/node_modules/iobroker.homee/node_modules/homee-api/homee.js:184:17)
homee.0 | 2018-08-17 15:58:04.129 | info | terminating
homee.0 | 2018-08-17 15:58:04.126 | warn | Exception: TypeError: Cannot read property 'send' of null
homee.0 | 2018-08-17 15:58:04.123 | info | cleaned everything up...
homee.0 | 2018-08-17 15:58:04.121 | error | at processImmediate [as _immediateCallback] (timers.js:617:5)
homee.0 | 2018-08-17 15:58:04.121 | error | at tryOnImmediate (timers.js:645:5)
homee.0 | 2018-08-17 15:58:04.121 | error | at runCallback (timers.js:672:20)
homee.0 | 2018-08-17 15:58:04.121 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3429:38)
homee.0 | 2018-08-17 15:58:04.121 | error | at Adapter.emit (events.js:191:7)
homee.0 | 2018-08-17 15:58:04.121 | error | at emitTwo (events.js:106:13)
homee.0 | 2018-08-17 15:58:04.121 | error | at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.homee/main.js:127:11)
homee.0 | 2018-08-17 15:58:04.121 | error | at Homee.setValue (/opt/iobroker/node_modules/iobroker.homee/node_modules/homee-api/homee.js:274:14)
homee.0 | 2018-08-17 15:58:04.121 | error | at Homee.send (/opt/iobroker/node_modules/iobroker.homee/node_modules/homee-api/homee.js:184:17

**Comment by Apollon77** [comment]
Do you also have more logs .. especially from before where the connection got lost ... there should be more

**Comment by Apollon77** [comment]
Please check again with 1.0.0 from GitHub
