### ISSUE TITLE
Groups from Homee?

### ISSUE THREAD

**Issue by mickyboys** [Apollon77/ioBroker.homee#11]
Hi, it would be beneficial to transfer Homee groups to ioBroker. Currently, it doubles the work since you need to create groups in ioBroker again although there already created in Homee. Since you have often more the one light bulb to be turned on/off with one button is would simply help.

**Comment by Apollon77** [comment]
I checked the functionality and it seems that also Homee App only iterate through the atached objects in the group to send the changes ... also there is no "value" of the group ... hm ...
