### ISSUE TITLE
Change State-Roles for ElectricMotorMeteringSwitch (e.g. fibaro roller shutter 2)

### ISSUE THREAD

**Issue by Seraphis411** [Apollon77/ioBroker.homee#13]
The role for the state "Position" (0-100%) is at the moment "level", but should better be "level.blind".

The state "ShutterBlindMode" instead is a state which gets set one time and defines if the connected device is a jalousie, a shutter blind, a garage door... It's function is comparable to the state "switch type" and should therefore also be changed to the role "sensor".

**Comment by Apollon77** [comment]
Can you please add the object definition of the created object for both cases?

You get them at "Objects" and then using the "pensil" icon in the line of the object and then copy the JSON from "Raw" Tab please. Thank you

**Comment by Apollon77** [comment]
Please check 1.0.0 from GitHub

**Comment by Seraphis411** [comment]
fixed, no need for further changes
