### ISSUE TITLE
Error: cannot recieve access token, recieved status 401

### ISSUE THREAD

**Issue by kurzreini** [Apollon77/ioBroker.homee#16]
Hallo!
Habe leider das Problem, dass der Adapter gelb bleibt. Beim erneuten starten kommt im Log folgende Fehlermeldung:

Error: cannot recieve access token, recieved status 401

Kann mir bitte jemand helfen???

**Comment by Apollon77** [comment]
Login Daten sind korrekt?

**Comment by kurzreini** [comment]
Ja sind korrekt... Hab den Adapter soeben neu installiert... Klappt alles wieder...

Danke!!!
