### ISSUE TITLE
No connection with Homee ID, IP to Homee

### ISSUE THREAD

**Issue by KrisKross89** [Apollon77/ioBroker.homee#168]
**Describe the bug**  
No connection to device

**To Reproduce**  
Reset, re-install not working, IP and user correct with password

**Versions:**  
 - Adapter version: latest
 - JS-Controller version: latest
 - Node version: latest
 - Operating system: iobroker on Proxmox

Additionally the settings cannot be saved in the adapter from time to time...

**Comment by Apollon77** [comment]
Please provide more details like screenshots and logs. No issues known!

**Comment by KrisKross89** [comment]
- tries for connection establish until timeout (1,2,3…)
- Adapter remains orange 
- Adapter Setting partially not possible to save or change

**Comment by Apollon77** [comment]
Please enable debug logging and send debug log. Else I can only repeat my last message: DETAILS PLEASE
