### ISSUE TITLE
Homeegramm Read und write Status dauerhaft auf true setzen

### ISSUE THREAD

**Issue by bergjet** [Apollon77/ioBroker.homee#185]
Ich bekomme manchmal folgende Meldung:
`021-10-30 12:57:47.307 - warn: javascript.0 (8563) Read-only state "homee.0.Homee-0.Homeegrams.132.play" has been written without ack-flag with value "true"`

Wenn ich den "read und write Status" auf true setze, wir der wieder zurück gesetzt auf false.

`

{
--
  | "type": "state",
  | "common": {
  | "name": "play",
  | "role": "button",
  | "type": "boolean",
  | "read": false,
  | "write": false
  | },
  | "native": {
  | "id": 132,
  | "name": "Bad Lüfter"
  | },
  | "_id": "homee.0.Homee-0.Homeegrams.132.play",
  | "acl": {
  | "object": 1636,
  | "state": 1636,
  | "owner": "system.user.admin",
  | "ownerGroup": "system.group.administrator"
  | },
  | "from": "system.adapter.homee.0",
  | "user": "system.user.admin",
  | "ts": 1635591467479
  | }

`
Wie bleibt denn das dauerhaft auf true?

**Versions:**  
 - Adapter version: <1.2.0>
 - JS-Controller version: <3.3.18>
 - Node version: <12.22.7>
 - Operating system: <Raspberry Pi4>

**Comment by Apollon77** [comment]
Am Ende ist das ein "trigger state" wie ein Button. Andere user wollten das der wieder auf false zurückspringt nachdem es gestartet wurde. Warum sollte er auf true bleiben?

**Comment by bergjet** [comment]
Weil ich dann immer die oben geschriebene Warnmeldung bekomme. Ich löse das homeegram (play=true) über ein script aus.

**Comment by Apollon77** [comment]
Ok, now i got it. If the "Play" state is allowed to be written depends on the fact if the Homeegram is configured as a "swich-Trigger". If not the wriiting is not allowed. So how it is configured?

**Comment by bergjet** [comment]
> So how it is configured?

How and where can I see that?

**Comment by Apollon77** [comment]
I assume in the app? I have no homee running atm but I remember that there was a setting if the homeegram should be shown as switch to start ...

**Comment by Apollon77** [comment]
Then I need a full debug log from adapterstart where all the json data that were loaded from homee are included. Grb file from disk at /opt/iobroker/logs/... and send via email to iobroker@fischer-ka.de with reference incl. number to this issue. And tell which homegreamm it is about

**Comment by bergjet** [comment]
Bei mir geht es noch nicht.

**Comment by bergjet** [comment]
Problem besteht noch immer.

**Comment by bergjet** [comment]
Keine Änderungen
