### ISSUE TITLE
homee connection error: "Error: connect EHOSTUNREACH 192.168.178.45:7681"

### ISSUE THREAD

**Issue by SlipKoRn88** [Apollon77/ioBroker.homee#189]
Hallo,
in den ioBroker Logs wird mir seit einigen Tagen folgender Fehler angezeigt:

homee connection error: "Error: connect EHOSTUNREACH 192.168.178.45:7681"

Homee Adapter Version: v1.2.0

**Comment by Apollon77** [comment]
EHOSTUNREACH means that the host /IP is not reachable in your network. Check the configuration, WLAN reachability and maybe reboot the Homee cube ...

**Comment by SlipKoRn88** [comment]
Das ist seltsam. Die Einstellungen sind korrekt, den Cube habe ich bereits mehrmals neu gestartet. Homee ist auch trotz der Fehlermeldung über die Homee App und auch über ioBroker erreichbar

**Comment by Apollon77** [comment]
Dann vllt den ioBroker Host mal neu starten? Bzw versuch mal von der Shell die IP anzupingen ...
