### ISSUE TITLE
Change color on DimmableExtendedColorLight-10 (Hue Lightstrip) bugs when off or dimmed to 0

### ISSUE THREAD

**Issue by C4b4nossi** [Apollon77/ioBroker.homee#23]
Hello,
I think I found a bug with the "DimmableExtendedColorLight-10" (Hue Lightstrip):

changing the Color (Color-101) (f.e. typing ff0000 + Enter) will not apply to the lightstrip when it is turned off (OnOff-98 = 0) or Dimmed to "0" (DimmingLevel-99)

Figured that out in a blinking-script. For the moment i work around with:
Dimming to 1; Turning on; do all the settings: colour, color-temp, on/off; Dimm Up with delay

Setting all values directly in homee works fine.

**Comment by Apollon77** [comment]
Can yopu please set the adapter to debug mode and then do the same (only change the dimming value!!?) using Homee App and post debug log? Question is which changes the App is sending ... because the adapter can not know "specialities of the device". So in worst case you need to know it and work around it somehow.

**Comment by C4b4nossi** [comment]
Thx for the quick response! I just checked the log and actions in the homee App: Homee itself is acting exactly the same way the adapter does. So nothing is wrong with the adapter!

When changing the color in the Homee App while the lightstrip is turned off or Dimmed to "0" - the color is displayed correctly in the App, but is not applied to the lightstrip. I didn't notice this when opening the issue in the 1st place. Sorry ..
Will address this to the homee-guys

**Comment by Apollon77** [comment]
Thank you for checking again!
