### ISSUE TITLE
Absturz des Adapters beim Wechsel des Homee Modus

### ISSUE THREAD

**Issue by masc3660** [Apollon77/ioBroker.homee#25]
Sobald der Datenpunkt "homee.0.Homee-0.HomeeMode-1" im ioBroker geändert wird, stürzt der Adapter ab und startet neu. Geplant ist, den Status "Zuhause", "Schlafend", "Abwesend" und "Urlaub" über eine grafische Oberfläche (Vis, HabPanel) per Button zu setzen.

Der Datenpunkt ist nach dem Neustart unverändert auf dem zuvor eingestellten Wert.

Hierzu der Auszug aus dem Log:

> 
> homee.0	2019-05-08 10:47:27.271	info	starting. Version 0.3.2 in /opt/iobroker/node_modules/iobroker.homee, node: v8.15.1
> host.ioBroker-RasPi	2019-05-08 10:47:25.583	info	instance system.adapter.homee.0 started with pid 14973
> host.ioBroker-RasPi	2019-05-08 10:46:55.565	info	Restart adapter system.adapter.homee.0 because enabled
> host.ioBroker-RasPi	2019-05-08 10:46:55.565	error	instance system.adapter.homee.0 terminated with code 0 (OK)
> Caught	2019-05-08 10:46:55.564	error	by controller[0]: at processImmediate [as _immediateCallback] (timers.js:745:5)
> Caught	2019-05-08 10:46:55.564	error	by controller[0]: at tryOnImmediate (timers.js:768:5)
> Caught	2019-05-08 10:46:55.564	error	by controller[0]: at runCallback (timers.js:810:20)
> Caught	2019-05-08 10:46:55.563	error	by controller[0]: at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3709:38)
> Caught	2019-05-08 10:46:55.563	error	by controller[0]: at Adapter.emit (events.js:214:7)
> Caught	2019-05-08 10:46:55.563	error	by controller[0]: at emitTwo (events.js:126:13)
> Caught	2019-05-08 10:46:55.562	error	by controller[0]: at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.homee/main.js:115:32)
> Caught	2019-05-08 10:46:55.560	error	by controller[0]: TypeError: Cannot read property 'type' of undefined
> homee.0	2019-05-08 10:46:55.515	warn	Exception: TypeError: Cannot read property 'type' of undefined
> homee.0	2019-05-08 10:46:55.509	info	DISCONNECTED: "closed by user request"
> homee.0	2019-05-08 10:46:55.505	info	cleaned everything up...
> homee.0	2019-05-08 10:46:55.501	error	at processImmediate [as _immediateCallback] (timers.js:745:5)
> homee.0	2019-05-08 10:46:55.501	error	at tryOnImmediate (timers.js:768:5)
> homee.0	2019-05-08 10:46:55.501	error	at runCallback (timers.js:810:20)
> homee.0	2019-05-08 10:46:55.501	error	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3709:38)
> homee.0	2019-05-08 10:46:55.501	error	at Adapter.emit (events.js:214:7)
> homee.0	2019-05-08 10:46:55.501	error	at emitTwo (events.js:126:13)
> homee.0	2019-05-08 10:46:55.501	error	at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.homee/main.js:115:32)
> homee.0	2019-05-08 10:46:55.501	error	TypeError: Cannot read property 'type' of undefined
> homee.0	2019-05-08 10:46:55.500	error	uncaught exception: Cannot read property 'type' of undefined

**Comment by Apollon77** [comment]
Bitte 1.0.0 vom Github versuchen und ggf neues Error log posten

**Comment by Seraphis411** [comment]
War vor der V0.5 auf jeden Fall ein vorhandener Bug, ist inzwischen aber gefixt

**Comment by Apollon77** [comment]
Danke
