### ISSUE TITLE
Adapterkonfiguration fehlerhaft

### ISSUE THREAD

**Issue by memooox3** [Apollon77/ioBroker.homee#4]
Nach Installation ders Adapters und der instanz ist es mir nicht möglich, die Adapterkonfiguration zu bearbeiten. Wo man die IP/die homee ID eintragen soll nach der Instanzinstallation kommt die Meldung "File index.html not found". Löschen und neu Installation hat nichts gebracht. So kann ich leider den Adapter (noch) nicht testen.

Auszug aus dem Log:

homee.0 | 2018-07-04 17:20:36.885 | error | Error: Error while receiving AccessToken: Error: connect ECONNREFUSED 127.0.0.1:7681
-- | -- | -- | --
homee.0 | 2018-07-04 17:20:36.797 | info | Init homee 127.0.0.1 for user
homee.0 | 2018-07-04 17:20:36.753 | info | starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.homee, node: v8.10.0
iobroker | 2018-07-04 17:20:34.963 | info | exit 0
iobroker | 2018-07-04 17:20:34.943 | info | host.raspberrypi object system.adapter.homee.0 created
host.raspberrypi | 2018-07-04 17:20:34.925 | info | instance system.adapter.homee.0 started with pid 20002
host.raspberrypi | 2018-07-04 17:20:34.900 | info | object change system.adapter.homee.0
iobroker | 2018-07-04 17:20:34.860 | info | host.raspberrypi object system.adapter.homee.0.alive created
iobroker | 2018-07-04 17:20:34.825 | info | host.raspberrypi object system.adapter.homee.0.connected created
iobroker | 2018-07-04 17:20:34.790 | info | host.raspberrypi object system.adapter.homee.0.memHeapUsed created
iobroker | 2018-07-04 17:20:34.759 | info | host.raspberrypi object system.adapter.homee.0.memHeapTotal created
iobroker | 2018-07-04 17:20:34.728 | info | host.raspberrypi object system.adapter.homee.0.memRss created
iobroker | 2018-07-04 17:20:34.696 | info | host.raspberrypi object system.adapter.homee.0.uptime created
iobroker | 2018-07-04 17:20:34.664 | info | host.raspberrypi object system.adapter.homee.0.inputCount created
iobroker | 2018-07-04 17:20:34.632 | info | host.raspberrypi object system.adapter.homee.0.outputCount created
iobroker | 2018-07-04 17:20:34.600 | info | host.raspberrypi object homee.0.info created
iobroker | 2018-07-04 17:20:34.570 | info | host.raspberrypi object homee.0.info.connection created
iobroker | 2018-07-04 17:20:34.563 | info | host.raspberrypi create instance homee
iobroker | 2018-07-04 17:20:34.531 | info | host.raspberrypi object system.adapter.homee created
mqtt.0 | 2018-07-04 17:20:34.493 | warn | Cannot resolve topic name for ID: system.adapter.homee.upload (object not found)
iobroker | 2018-07-04 17:20:34.422 | info | upload [0] homee.admin /opt/iobroker/node_modules/iobroker.homee/admin/custom_m.html custom_m.html text/html
iobroker | 2018-07-04 17:20:34.351 | info | upload [1] homee.admin /opt/iobroker/node_modules/iobroker.homee/admin/homee.png homee.png image/png
iobroker | 2018-07-04 17:20:34.286 | info | upload [2] homee.admin /opt/iobroker/node_modules/iobroker.homee/admin/index_m.html index_m.html text/html
iobroker | 2018-07-04 17:20:34.206 | info | upload [3] homee.admin /opt/iobroker/node_modules/iobroker.homee/admin/words.js words.js application/javascript
iobroker | 2018-07-04 17:20:34.179 | info | got /opt/iobroker/node_modules/iobroker.homee/admin
iobroker | 2018-07-04 17:20:17.407 | info | npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.homee"
iobroker | 2018-07-04 17:20:17.403 | info | host.raspberrypi install adapter homee
iobroker | 2018-07-04 17:20:16.182 | info | add homee
host.raspberrypi | 2018-07-04 17:19:42.882 | info | Update repository "default" under "http://download.iobroker.net/sources-dist.json"
iobroker | 2018-07-04 17:19:42.283 | info | exit 0
iobroker | 2018-07-04 17:18:32.558 | info | npm install https://github.com/Apollon77/ioBroker.homee/tarball/master --production --prefix "/opt/iobroker" (System call)
iobroker | 2018-07-04 17:18:32.321 | info | install https://github.com/Apollon77/ioBroker.homee/tarball/master
iobroker | 2018-07-04 17:18:31.351 | info | url "https://github.com/Apollon77/ioBroker.homee"

**Comment by Apollon77** [comment]
Der Adapter unterstützt nur Admin3 !! Bittt Admin updaten.
