### ISSUE TITLE
Farbwert aktuell als dezimalzahl statt als hex

### ISSUE THREAD

**Issue by Seraphis411** [Apollon77/ioBroker.homee#5]
Der Farbwert wird durch homee/den Adapter aktuell als dezimalzahl geliefert, die für vis verfügbaren Colopicker geben den RGB-Farbwert allerdings als hex-Wert inkl. vorgestelltem # aus.

Das senden einen solchen hex-Wertes an homee führt zu folgendem Fehler im Log:

`homee.0	2018-07-11 20:31:32.728	error	homee connection error: "value must be a number"`

Die Farbe des Lichtes ändert sich in diesem Fall nicht. Wird als Farbe eine Dezimalzahl an homee gesendet, wird diese korrekt übernommen.

Objektdefinition color einer RGB-Leuchte homee.0.DimmableColorLight-53.Color-342

```
{
  "type": "state",
  "common": {
    "name": "Wohnzimmer Iris.Color",
    "type": "number",
    "unit": "RGB",
    "min": 0,
    "max": 16777215,
    "read": true,
    "write": true,
    "role": "level.color.rgb",
    "custom": {
      "homee.0": {
        "enabled": true
      }
    }
  },
  "native": {
    "id": 342,
    "node_id": 53,
    "type": 23
  },
  "from": "system.adapter.homee.0",
  "ts": 1531252790733,
  "_id": "homee.0.DimmableColorLight-53.Color-342",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

Objektdefinition color eines RGBW-Stripes homee.0.DimmableExtendedColorLight-11.Color-92

```
{
  "type": "state",
  "common": {
    "name": "Schlafzimmer Stripe-Bett.Color",
    "type": "number",
    "unit": "RGB",
    "min": 0,
    "max": 16777215,
    "read": true,
    "write": true,
    "role": "level.color.rgb",
    "custom": {
      "homee.0": {
        "enabled": true
      }
    }
  },
  "native": {
    "id": 92,
    "node_id": 11,
    "type": 23
  },
  "from": "system.adapter.homee.0",
  "ts": 1531252790530,
  "_id": "homee.0.DimmableExtendedColorLight-11.Color-92",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by Apollon77** [comment]
Scheinbar kann ich also für Unit RGB was besonderes einbauen ;-)

**Comment by Apollon77** [comment]
Hast Du mal (muss wissen wie Homee die Nummer berechnet) die Info welche farbe du in der Homee-App wähst (also der Hex-Code #123456) und elche Zahl dann in ioBroker auftaucht ?!

**Comment by Apollon77** [comment]
Bitte 0.3.0 vom Github testen. Die Umrechnung "Hex in Zahl" hab ich  jetzt mal auf eine von zwei arten gemacht. Jetzt bitte schauen ob es passt oder ob die RGB verdreht auf BGR sind. Feedback bitte!

Am besten alle Homee Datenpunkte mit RGB als Unit vorher löschen

**Comment by Apollon77** [comment]
Bitte falls schon geupdated vor 0:30 ... nochmal" Da war noch ein Bug!

**Comment by Seraphis411** [comment]
Die Umrechnung klappt jetzt soweit 👍 wie du aber schon befürchtet hast sind Rot und Blau vertauscht, also BGR statt RGB. Wenn ich im homee für eine Leuchte die Farbe Blau einstelle erhalte ich in iobroker momentan also den Wert #ff0000 statt #0000ff, andersrumm mit Farbwahl über einen colorpicker in vis führt das dann natürlich auch zu z.B. Rot statt Blau im homee.

**Comment by Apollon77** [comment]
Naja, war ne 50/50 Chance ;-) fixe ich heute Abend.

**Comment by Apollon77** [comment]
Bitte vom Github updaten (version bleibt gleich), danach Neustart der Instanz nicht vergessen. Passts jetzt in beiden Richtungen?

**Comment by Seraphis411** [comment]
Eben getestet, passt jetzt und das auch in beide Richtungen. Danke

**Comment by Apollon77** [comment]
Bitte Forum Thread  zum Adapter beobachten. Ich schreibe dort wenn die Version offiziell fertig ist. Dann bitte nochmal updaten!!!!
