### ISSUE TITLE
Error: cannot receive access token, received status 401

### ISSUE THREAD

**Issue by bergjet** [Apollon77/ioBroker.homee#53]
Habe die Version 1.0.5
Nun habe ich den JS-Controller upgedatet auf 3.0.14
Jetzt der Fehler "Error: cannot receive access token, received status 401"

Einen neuen User in homee habe ich schon angelegt, hilft aber nichts.

**Comment by bergjet** [comment]
Habe den Adapter gelöscht und neu installiert.
Jetzt kann ich die Konfiguration (IP, User, Passwort) nicht mehr speichern. Der Button ist zwar da, aber man kann ihn nicht anklicken.

**Comment by cru8602** [comment]
Habe das selbe Problem. nach Update des JS_controlers kam der Fehler "Error: cannot receive access token, received status 401" und nach Neuinstallation des Adapters lässt sich dieser nicht mehr konfigurieren.

**Comment by wick35** [comment]
Ich hatte das selbe Problem, hab die Version 1.04 wieder installiert, ging.
Habs noch mal auf die 1.0.5 upgedate, hat dann funktioniert. Nach einem Neustart vom ioBroker wieder der selbe Fehler...

**Comment by Apollon77** [comment]
Bitte Admin 4.0.9 Nutzen und mal das Passwort im Admin neu Eingaben und speichern. Tut es dann?

**Comment by cru8602** [comment]
Bin schon auf admin 4.0.9. Adapter lässt sich nach Neuinstallation nicht einrichten. Davor hat neue pw Eingabe aber auch keine Besserung gebracht.

**Comment by bergjet** [comment]
Admin 4.0.9 und neues Passwort. Konfiguration nicht möglich.
https://www.dropbox.com/s/8l485pqvvx5o0wk/Ohne%20Titel.mp4?dl=0

**Comment by bergjet** [comment]
homee Adapter V1.0.1 funktioniert.

**Comment by Coffee-lover** [comment]
Ich habe das gleiche Problem und nun die "Lösung" von bergjet mit der 1.0.1. umschifft.

**Comment by danieldriessen** [comment]
Ich habe ebenfalls exakt das gleiche Problem und konnte es auch vorerst mir der v1.0.1 umgehen.

**Comment by Apollon77** [comment]
Nutzt ihr js-Controller 3? Falls ja bitte entweder auf die 3.0.19 warten oder „iobroker upload homee“ versuchen. Geht es dann? Ggf Passwort im Admin neu eintippen.

**Comment by bergjet** [comment]
JS-Controller 3.0.14
Warte auf 3.0.19

**Comment by Apollon77** [comment]
3.0.19 auf npm, ab morgen früh dann im Latest Repo

**Comment by Apollon77** [comment]
Bitte die 1.0.6 versuchen. Im zweifel passwort neu eingeben (das sollte jetzt weder tun)

**Comment by Apollon77** [comment]
1.0.7 is better
