### ISSUE TITLE
I cannot save the settings in homee

### ISSUE THREAD

**Issue by DRIOB** [Apollon77/ioBroker.homee#57]
Hello,

I cannot save the settings by homee.

What ist the Problem

Platform: linux
os: linux
Architecture: x64
CPUs: 2
Speed: 2001 MHz
Model: Intel(R) Celeron(R) CPU J3355 @ 2.00GHz
RAM: 9.5 GB 
System uptime: 07:25:17
Node.js: v12.16.2
NPM: 6.14.4
adapters count: 346
Disk size: 2.6 TiB
Disk free: 1.5 TiB
Uptime: 04:36:25
Active instances: 38

Thank You

**Comment by Apollon77** [comment]
What exactly you mean? Is the save button greyed out? The. You need to change a value ... no change, no save needed. Or provide more info about your problem.

**Comment by Apollon77** [comment]
And: Which Admin version? Which js-controller version?

**Comment by DRIOB** [comment]
Sorry for my late answer, because i was sick.

Admin = ioBroker.admin 4.1.1
js-controller = Installiert: 3.0.20

Thanks

**Comment by Apollon77** [comment]
But what answers to the first question?

**Comment by DRIOB** [comment]
> 
> 
> But what answers to the first question?

Answer to the first question = I can enter the data, but if I click on save or save and close it will not be carried out Thanks

**Comment by Apollon77** [comment]
Can you please check browser error console if an error is shown?

**Comment by DRIOB** [comment]
Hi,
i get this with Firefox (76.0 (32-Bit)):
TypeError: value is undefined
index_m.html:36:24
    encrypt http://192.168.178.22:12123/adapter/homee/index_m.html?0:36
    saveSettings http://192.168.178.22:12123/js/adapter-settings.js:259
    onack http://192.168.178.22:12123/socket.io/socket.io.js:8
    onpacket http://192.168.178.22:12123/socket.io/socket.io.js:8
    exports http://192.168.178.22:12123/socket.io/socket.io.js:8
    emit http://192.168.178.22:12123/socket.io/socket.io.js:6
    ondecoded http://192.168.178.22:12123/socket.io/socket.io.js:6
    exports http://192.168.178.22:12123/socket.io/socket.io.js:8
    emit http://192.168.178.22:12123/socket.io/socket.io.js:6
    add http://192.168.178.22:12123/socket.io/socket.io.js:6
    ondata http://192.168.178.22:12123/socket.io/socket.io.js:6
    exports http://192.168.178.22:12123/socket.io/socket.io.js:8
    emit http://192.168.178.22:12123/socket.io/socket.io.js:6
    onPacket http://192.168.178.22:12123/socket.io/socket.io.js:7
    setTransport http://192.168.178.22:12123/socket.io/socket.io.js:7
    emit http://192.168.178.22:12123/socket.io/socket.io.js:6
    onPacket http://192.168.178.22:12123/socket.io/socket.io.js:7
    onData http://192.168.178.22:12123/socket.io/socket.io.js:7
    onmessage http://192.168.178.22:12123/socket.io/socket.io.js:8
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://e9006ded-ab9f-42d8-bd6c-62e9c007c3d1/lib/tp/browser-polyfill.min.js
Source-Map-Adresse: browser-polyfill.min.js.map

TypeError: value is undefined
index_m.html:36:24
    encrypt http://192.168.178.22:12123/adapter/homee/index_m.html?0:36
    saveSettings http://192.168.178.22:12123/js/adapter-settings.js:259
    onack http://192.168.178.22:12123/socket.io/socket.io.js:8
    onpacket http://192.168.178.22:12123/socket.io/socket.io.js:8
    exports http://192.168.178.22:12123/socket.io/socket.io.js:8
    emit http://192.168.178.22:12123/socket.io/socket.io.js:6
    ondecoded http://192.168.178.22:12123/socket.io/socket.io.js:6
    exports http://192.168.178.22:12123/socket.io/socket.io.js:8
    emit http://192.168.178.22:12123/socket.io/socket.io.js:6
    add http://192.168.178.22:12123/socket.io/socket.io.js:6
    ondata http://192.168.178.22:12123/socket.io/socket.io.js:6
    exports http://192.168.178.22:12123/socket.io/socket.io.js:8
    emit http://192.168.178.22:12123/socket.io/socket.io.js:6
    onPacket http://192.168.178.22:12123/socket.io/socket.io.js:7
    setTransport http://192.168.178.22:12123/socket.io/socket.io.js:7
    emit http://192.168.178.22:12123/socket.io/socket.io.js:6
    onPacket http://192.168.178.22:12123/socket.io/socket.io.js:7
    onData http://192.168.178.22:12123/socket.io/socket.io.js:7
    onmessage http://192.168.178.22:12123/socket.io/socket.io.js:8

​

**Comment by Apollon77** [comment]
Ok, we come closer :-) Which Admin version?

**Comment by DRIOB** [comment]
Admin = ioBroker.admin 4.1.1
js-controller = Installiert: 3.0.20
