### ISSUE TITLE
Homee and iobroker Connection error after update

### ISSUE THREAD

**Issue by Joker1385** [Apollon77/ioBroker.homee#58]
dear i installed 1.0.5 an then i have in iobroker error

Error: cannot receive access token, received status 401

check ip: is ok
check username 🆗 
change ip to id the same 

my system is intel nuc 
now i make a restor and check the problem again

**Comment by Apollon77** [comment]
Which admin version? Which js Controller Version?

**Comment by Apollon77** [comment]
Please try Admin 4.0.9 and js.controller 3.0.19

**Comment by Joker1385** [comment]
admin 4.1.1 and Node.js: v12.16.2  js.controller 3.0.19 how can i downgrade admin ?

**Comment by Joker1385** [comment]
aaa i found npm install iobroker.admin@4.0.9 but the problem is the same - i found the error

my router give iobroker a new IP after update and reboot - i say my router you give iobroker the old IP and restore all datas by a day before now works thx alot

**Comment by Apollon77** [comment]
Ok, was mor meaned "at least Admin 4.0.9"

**Comment by Apollon77** [comment]
Bitte die 1.0.6 versuchen. Im zweifel passwort neu eingeben (das sollte jetzt weder tun)

**Comment by Apollon77** [comment]
1.0.7. is better :-)
