### ISSUE TITLE
Request: Homeegramme aktivieren/deaktivieren

### ISSUE THREAD

**Issue by Seraphis411** [Apollon77/ioBroker.homee#6]
In homee selbst gibt es keine Variablen und das aktivieren/deaktiveren von Homeegrammen ist die einzige Möglichkeit, diesen Mangel halbwegs zu umgehen.. Könnte man aus iobroker heraus HGs aktivieren/deaktiveren, so hätte man die Möglichkeit, (boolesche) Werte in homee bereitstellen, oder eben auch aus homee zu empfangen.

Für Leute, die den homee nur noch als Gateway verwenden, ist das natürlich uninteressant. Für die, die iobroker hauptsächlich für komplexere Logik, die Anbindung weiterer Geräte oder auch als Visualisierung verwenden, wäre so eine Schnittstelle aber sicher sinnvoll.

**Comment by Apollon77** [comment]
bitte 0.3.0 vom Github testen

**Comment by Apollon77** [comment]
Am besten vorher unter Homee-0.Homeegramms alle Objekte löschen

**Comment by Apollon77** [comment]
Bitte falls schon geupdated vor 0:30 ... nochmal" Da war noch ein Bug!

**Comment by Seraphis411** [comment]
Funktioniert perfekt, so hab ichs mir vorgestellt ;-)
Super auch mit dem Button für den simulierten Tastendruck bzw. den entsprechend gesetzten Berechtigungen je nachdem ob das Abspielen in homee als möglicher Auslöser gesetzt ist (gabs ja davor schon)

**Comment by Apollon77** [comment]
Bitte Forum Thread  zum Adapter beobachten. Ich schreibe dort wenn die Version offiziell fertig ist. Dann bitte nochmal updaten!!!!
