### ISSUE TITLE
Sorry I have to bring the problem out again as it still exists -  I cannot save the settings in homee

### ISSUE THREAD

**Issue by DRIOB** [Apollon77/ioBroker.homee#63]
**I cannot save the settings in homee**

https://github.com/Apollon77/ioBroker.homee/issues/57

Sorry I have to bring the problem out again as it still exists.

Thanks

**Comment by Apollon77** [comment]
yes known, need to find time to check and fix

**Comment by SteffenPWH** [comment]
same her.
after upgrade to 
- npm 6.14.4
- node/nodejs 12.17.0
- iOBroker.admin 4.1.1
![image](https://user-images.githubusercontent.com/66113312/83238751-2caeac80-a197-11ea-997c-af7fea874ac1.png)

**Comment by DRIOB** [comment]
> 
> 
> yes known, need to find time to check and fix

Hi Apollon,

Sorry i can`t use homee wit iobroker. Is there any chance to fix this Thanks and Sorry for the Hurry. Best regards DRIOB

**Comment by blackeye11** [comment]
Hi Apollon, 
I have the same issue / problem like DRIOB: 
I am quite new to iobroker, but I am an "old" homee-user.  I have installed iobroker on a new Raspi 4B with 4GB memory and updated everything to the lastest version. 

Platform: linux
os: linux
Architecture: x64
Model: RASP PI 4 B 4GB Raspberry Pi 4 B, 4x 1,5 GHz, 4 GB RAM, WLAN, BT
Admin: v4.1.1
Node.js: v12.18.0
NPM: v6.14.4
js-controller: v3.1.5
homee:  1.0.5

If I try to enter the cridentials for the homee-adapter, I can fill out the 3 fields "home-ID / Hostname / IP", "user name" and "Password" and press the available [Save] button (or [Save & Close] button, but the no reaction is happening. It seems, that the buttons are just pictures without any events behind. 
I tried with the homee's local ip-address and with the homee-id, but the behaviour is always the same. 

The browser console brings the following error:
DevTools failed to load SourceMap: Could not load content for chrome-extension://mmhlniccooihdimnnjhamobppdhaolme/lib/tp/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
Uncaught TypeError: Cannot read property 'length' of undefined
    at encrypt (index_m.html?0:36)
    at r.<anonymous> (VM184 adapter-settings.js:259)
    at r.onack (index.js:83)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.ondecoded (index.js:83)
    at a.<anonymous> (index.js:83)
    at a.r.emit (index.js:83)
    at a.add (index.js:83)
encrypt @ index_m.html?0:36
(anonymous) @ adapter-settings.js:259
r.onack @ index.js:83
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83

**Comment by DRIOB** [comment]
**Push!**


    yes known, need to find time to check and fix

Hi Apollon,

Sorry i can`t use homee wit iobroker. Is there any chance to fix this Thanks and Sorry for the Hurry. Best regards DRIOB

**Comment by Apollon77** [comment]
Bitte die 1.0.6 versuchen. Im zweifel passwort neu eingeben (das sollte jetzt weder tun)

**Comment by SteffenPWH** [comment]
Ich krieg die Installation ohne IoBroker nicht hin... sorry... wenn ich den Link zur code.zip eingebe, passiert nix. :(
in IoBroker wird mir die 1.0.6 nicht angezeigt 
![image](https://user-images.githubusercontent.com/66113312/84452385-00466600-ac56-11ea-91e3-a78c338a8c55.jpeg)

**Comment by DRIOB** [comment]
No, i cant save the password.

**Comment by Apollon77** [comment]
Which admin version and which js-controller? Any error in the browser console?

Please also try „iobroker upload homee“ and try again.

**Comment by DRIOB** [comment]
Hi,

 

anbei der Auszug der Web Konsole:

 

TypeError: key is undefined index_m.html:41:13

    encrypt http://192.168.178.13:8081/adapter/homee/index_m.html?0:41

    saveSettings http://192.168.178.13:8081/js/adapter-settings.js:259

    onack http://192.168.178.13:8081/socket.io/socket.io.js:8

    onpacket http://192.168.178.13:8081/socket.io/socket.io.js:8

    exports http://192.168.178.13:8081/socket.io/socket.io.js:8

    emit http://192.168.178.13:8081/socket.io/socket.io.js:6

    ondecoded http://192.168.178.13:8081/socket.io/socket.io.js:6

    exports http://192.168.178.13:8081/socket.io/socket.io.js:8

    emit http://192.168.178.13:8081/socket.io/socket.io.js:6

    add http://192.168.178.13:8081/socket.io/socket.io.js:6

    ondata http://192.168.178.13:8081/socket.io/socket.io.js:6

    exports http://192.168.178.13:8081/socket.io/socket.io.js:8

    emit http://192.168.178.13:8081/socket.io/socket.io.js:6

    onPacket http://192.168.178.13:8081/socket.io/socket.io.js:7

    setTransport http://192.168.178.13:8081/socket.io/socket.io.js:7

    emit http://192.168.178.13:8081/socket.io/socket.io.js:6

    onPacket http://192.168.178.13:8081/socket.io/socket.io.js:7

    onData http://192.168.178.13:8081/socket.io/socket.io.js:7

    onmessage http://192.168.178.13:8081/socket.io/socket.io.js:8



Und das (Please also try „iobroker upload homee“ and try again. ) ging auch nicht

D. Rottmann

E. - Mail: dr@rottmann-ffm.de <mailto:dr@rottmann-ffm.de> 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. Wir weisen darauf hin, dass derartige Nachrichten - mit und ohne Zutun von Dritten - verloren gehen, verändert oder verfälscht werden können. Wir haften deshalb nicht für die Unversehrtheit von E-Mails nachdem sie unseren Herrschaftsbereich verlassen haben und können Ihnen hieraus entstehenden Schaden nicht ersetzen. Sollte durch die Zusendung einer E-Mail von uns, trotz der von uns verwendeten Virus-Schutz-Programme, ein Virus in Ihre Systeme gelangen, haften wir nicht für eventuell hieraus entstehenden Schaden. Dieser Haftungsausschluss gilt nur soweit gesetzlich zulässig.

This E-Mail may contain confidential and/or privileged information. If you are not the intended recipient please notify the sender immediately and destroy this E-Mail. Any unauthorized copying, disclosure or distribution of the material in this E-Mail is strictly forbidden. We draw your attention to the fact that such messages can be lost, changed or falsified, with or without any interference by third persons. We cannot be responsible for the integrity of E-Mails after they have left our sphere of control. If, despite our use of anti-virus software, a virus enters your systems in connection with the sending of the e-Mail, you may not hold us liable for any damages that may possibly arise in that connection. We will accept liability which by law we cannot exclude. 

 

Von: Ingo Fischer <notifications@github.com> 
Gesendet: Freitag, 12. Juni 2020 14:54
An: Apollon77/ioBroker.homee <ioBroker.homee@noreply.github.com>
Cc: DRIOB <bestellung@rottmann-ffm.de>; Author <author@noreply.github.com>
Betreff: Re: [Apollon77/ioBroker.homee] Sorry I have to bring the problem out again as it still exists - I cannot save the settings in homee (#63)

 

Which admin version and which js-controller? Any error in the browser console?

Please also try „iobroker upload homee“ and try again.

**Comment by DRIOB** [comment]
Sorry,

 

ioBroker.admin 4.1.1

 

Betriebssystem

linux

Betriebssystem

linux

Architektur

arm64

CPUs

4

Geschwindigkeit

1296 MHz

Modell

unknown

RAM

3.9 GB

System Betriebszeit

00:46:18

Node.js

v12.18.0

NPM

6.14.4

Anzahl der Adapter

351

Festplatte Größe

227.17 GB

Festplatte frei

220.11 GB

Betriebszeit

00:12:50

Aktive Instanzen

39

Hi,

 

anbei der Auszug der Web Konsole:

 

TypeError: key is undefined index_m.html:41:13

    encrypt http://192.168.178.13:8081/adapter/homee/index_m.html?0:41

    saveSettings http://192.168.178.13:8081/js/adapter-settings.js:259

    onack http://192.168.178.13:8081/socket.io/socket.io.js:8

    onpacket http://192.168.178.13:8081/socket.io/socket.io.js:8

    exports http://192.168.178.13:8081/socket.io/socket.io.js:8

    emit http://192.168.178.13:8081/socket.io/socket.io.js:6

    ondecoded http://192.168.178.13:8081/socket.io/socket.io.js:6

    exports http://192.168.178.13:8081/socket.io/socket.io.js:8

    emit http://192.168.178.13:8081/socket.io/socket.io.js:6

    add http://192.168.178.13:8081/socket.io/socket.io.js:6

    ondata http://192.168.178.13:8081/socket.io/socket.io.js:6

    exports http://192.168.178.13:8081/socket.io/socket.io.js:8

    emit http://192.168.178.13:8081/socket.io/socket.io.js:6

    onPacket http://192.168.178.13:8081/socket.io/socket.io.js:7

    setTransport http://192.168.178.13:8081/socket.io/socket.io.js:7

    emit http://192.168.178.13:8081/socket.io/socket.io.js:6

    onPacket http://192.168.178.13:8081/socket.io/socket.io.js:7

    onData http://192.168.178.13:8081/socket.io/socket.io.js:7

    onmessage http://192.168.178.13:8081/socket.io/socket.io.js:8



Und das (Please also try „iobroker upload homee“ and try again. ) ging auch nicht

D. Rottmann

E. - Mail: dr@rottmann-ffm.de <mailto:dr@rottmann-ffm.de> 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. Wir weisen darauf hin, dass derartige Nachrichten - mit und ohne Zutun von Dritten - verloren gehen, verändert oder verfälscht werden können. Wir haften deshalb nicht für die Unversehrtheit von E-Mails nachdem sie unseren Herrschaftsbereich verlassen haben und können Ihnen hieraus entstehenden Schaden nicht ersetzen. Sollte durch die Zusendung einer E-Mail von uns, trotz der von uns verwendeten Virus-Schutz-Programme, ein Virus in Ihre Systeme gelangen, haften wir nicht für eventuell hieraus entstehenden Schaden. Dieser Haftungsausschluss gilt nur soweit gesetzlich zulässig.

This E-Mail may contain confidential and/or privileged information. If you are not the intended recipient please notify the sender immediately and destroy this E-Mail. Any unauthorized copying, disclosure or distribution of the material in this E-Mail is strictly forbidden. We draw your attention to the fact that such messages can be lost, changed or falsified, with or without any interference by third persons. We cannot be responsible for the integrity of E-Mails after they have left our sphere of control. If, despite our use of anti-virus software, a virus enters your systems in connection with the sending of the e-Mail, you may not hold us liable for any damages that may possibly arise in that connection. We will accept liability which by law we cannot exclude. 

 

Von: Ingo Fischer <notifications@github.com> 
Gesendet: Freitag, 12. Juni 2020 14:54
An: Apollon77/ioBroker.homee <ioBroker.homee@noreply.github.com>
Cc: DRIOB <bestellung@rottmann-ffm.de>; Author <author@noreply.github.com>
Betreff: Re: [Apollon77/ioBroker.homee] Sorry I have to bring the problem out again as it still exists - I cannot save the settings in homee (#63)

 

Which admin version and which js-controller? Any error in the browser console?

Please also try „iobroker upload homee“ and try again.

**Comment by Apollon77** [comment]
Try 1.0.7

**Comment by DRIOB** [comment]
Well done.

 

It`s function.

 

Best regards

 

D. Rottmann

E. - Mail: dr@rottmann-ffm.de <mailto:dr@rottmann-ffm.de> 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. Wir weisen darauf hin, dass derartige Nachrichten - mit und ohne Zutun von Dritten - verloren gehen, verändert oder verfälscht werden können. Wir haften deshalb nicht für die Unversehrtheit von E-Mails nachdem sie unseren Herrschaftsbereich verlassen haben und können Ihnen hieraus entstehenden Schaden nicht ersetzen. Sollte durch die Zusendung einer E-Mail von uns, trotz der von uns verwendeten Virus-Schutz-Programme, ein Virus in Ihre Systeme gelangen, haften wir nicht für eventuell hieraus entstehenden Schaden. Dieser Haftungsausschluss gilt nur soweit gesetzlich zulässig.

This E-Mail may contain confidential and/or privileged information. If you are not the intended recipient please notify the sender immediately and destroy this E-Mail. Any unauthorized copying, disclosure or distribution of the material in this E-Mail is strictly forbidden. We draw your attention to the fact that such messages can be lost, changed or falsified, with or without any interference by third persons. We cannot be responsible for the integrity of E-Mails after they have left our sphere of control. If, despite our use of anti-virus software, a virus enters your systems in connection with the sending of the e-Mail, you may not hold us liable for any damages that may possibly arise in that connection. We will accept liability which by law we cannot exclude. 

 

Von: Ingo Fischer <notifications@github.com> 
Gesendet: Freitag, 12. Juni 2020 22:39
An: Apollon77/ioBroker.homee <ioBroker.homee@noreply.github.com>
Cc: DRIOB <bestellung@rottmann-ffm.de>; Author <author@noreply.github.com>
Betreff: Re: [Apollon77/ioBroker.homee] Sorry I have to bring the problem out again as it still exists - I cannot save the settings in homee (#63)

 

Closed #63 <https://github.com/Apollon77/ioBroker.homee/issues/63> .
