### ISSUE TITLE
EnOcean roller shutters do not provide value of current position

### ISSUE THREAD

**Issue by mtb-z** [Apollon77/ioBroker.homee#65]
It looks like the homee-API or the adaptor is not providing the current shutter position when using EnOcean devices. The value for the object .position is static at 0% all time while you can set the position via a slider or button without any issues.
This behaviour does not affect Z-Wave devices.

**Comment by Apollon77** [comment]
Please enable debug logging and send debug log of a change of the decie, then we see whats in the data

**Comment by mtb-z** [comment]
I noticed in the logfile that no position changes are reported by homee. Also the position slider in the native homee frontend does not change the percentage.
Due to this behaviour I assume, it is not an issue in the homee adapter but caused by homee itself. 

Please find below the related debug logging 

`2020-06-18 22:25:23.743 - debug: homee.0 (29018) Value changed by homee for MeteringPlug-86.AccumulatedEnergyUse-826 => 83.919
2020-06-18 22:25:26.592 - debug: homee.0 (29018) Ignore value change for ShutterPositionSwitch-93.UpDown-849 = 4 (4 --> 1)
2020-06-18 22:25:26.851 - debug: homee.0 (29018) Ignore value change for ShutterPositionSwitch-93.UpDown-849 = 4 (4 --> 1)
2020-06-18 22:25:29.898 - debug: homee.0 (29018) Value changed by homee for ShutterPositionSwitch-93.UpDown-849 => 0`

**Comment by Apollon77** [comment]
Then exactly ...maybe wort a bugreport at Homee thta they can fix it?
