### ISSUE TITLE
Objekte mit Name und ohne Geräteart+Nummerierung

### ISSUE THREAD

**Issue by denzel1994** [Apollon77/ioBroker.homee#69]
**Is your feature request related to a problem? Please describe.**
Da ich öfters mal Geräte löschen und neu hinzufügen muss (bspw. durch das HomeeInHomee Feature) habe ich das Problem, dass sich jedes Mal der Objektpfad des entsprechenden Geräts vollständig ändert und ich all meine Skripte und Szenen wieder anpassen muss. 

Statt "homee.0.DimmableColorLight-64.OnOff-292" muss ich das Gerät dann unter "homee.0.DimmableColorLight-226.OnOff-712" ansprechen. Und ich muss die Objekt-Leiche "homee.0.DimmableColorLight-64" aus den Objekten löschen.

**Describe the solution you'd like**
Sehr gut wäre eine Option in der Adapterkonfiguration um die Objektstrukturierung anzupassen. So kann standardmäßig die bisherige Form bestehen bleiben, damit ein Update nicht die Konfiguration anderer Nutzer zerschießt. Zusätzlich könnte man auswählen, dass die Objekte der Geräte immer unter ihrem Gerätenamen angesprochen und nach erneutem Hinzufügen des Gerätes in Homee auch direkt wieder gefunden werden können. Also keine Auflistung der Geräte mit der Geräteart-AufsteigendeNummerierung, sondern der in Homee gewählte Gerätename.

**Describe alternatives you've considered**
-

**Additional context**
<img width="1265" alt="Bildschirmfoto 2020-06-19 um 17 09 53" src="https://user-images.githubusercontent.com/36551243/85149716-e9090900-b251-11ea-96be-8cea6ef2977f.png">

**Comment by Apollon77** [comment]
Ich habe lange hin und her experimentiert. Am Ende müssen Objekte eine Eindeutige ID haben und hier nummeriert homee halt Dinge "Nur" durch. Auch bin ich nicht sicher ob die Namen eindeutig sein müssen in Homee und am Ende kann es da zu Problemen kommen.

Im Zweifel kannst Du auch im JavaScript Adapter mit den Objektnamen arbeiten.

Ich glaube ich werde diese Änderung nicht machen aktuell. Sorry
