### ISSUE TITLE
Rollen der Device-States / Anpassung für Material UI

### ISSUE THREAD

**Issue by Seraphis411** [Apollon77/ioBroker.homee#7]
Einige der Rollen scheinen noch nicht optimal gewählt zu sein, zumindest im Zusammenspiel mit der aktuellen Beta des Material UI-Adapters (verwende das latest-repository, Stand heute damit admin 3.4.8, web 2.4.0, material 0.9.1).

Vorab: Hab selbst nicht besonders viel Erfahrung mit iobroker, schon gar nicht mit der korrekten Wahl von Rollen usw.. Ich habe jetzt erstmal nur ein wenig das Material UI geteset, Rollläden usw. bin ich jetzt noch nicht angegen. Bitte auch sagen, in welcher Form ich solche Infos wie die nachfolgenden am Besten liefern soll, also was für dich interessant ist.

**Z-Wave Fibaro-Dimmer**

Der state SwitchType war als Switch eingestellt, was dazu geführt hat, dass beim Schalten des Lichtes über das Material UI diese Einstellung auch angepasst wurde. (Einstellung gibt an ob lokal ein Schalter oder Taster angeschlossen ist).

Wenn der SwitchType auf Sensor o.ä. geändert wird funktioniert alles im Material UI.

![iobroker_dimmablemeteringswitch_fibaro-dimmer](https://user-images.githubusercontent.com/35173972/43037463-73b8d042-8d0d-11e8-8048-3159f4bf0d11.PNG)

**Hue Iris RGB-Leuchte**

OnOff und IdentificationMode sind als Rolle Level und Art Zahl angelegt. Beim Z-Wave-Dimmer sind die 0/1-Werte dagegen alle als Art Logik + Rolle Switch angelegt. Scheint Material UI gar nicht zu schmecken.
LinkQuality sollte evtl als Rolle Sensorwert sein?

Im MaterialUI steht der Dimmwert die ganze Zeit auf 2500%, keine State scheint einen Einfluss darauf zu haben. Beim ändern via Slider springt der Wert immer zurück auf 50%. Dimmwert 0 wird an homee beim Ausschalten via button gesendet, der Zustand anschließend scheint aber eine Rückmeldung zu fehlen (drehender Kringel verschwindet nicht). Auch der Ein/Aus-Zustand wird nicht angezeigt.

![iobroker_dimmablecolorlight_hue-iris](https://user-images.githubusercontent.com/35173972/43037568-c479ebaa-8d0e-11e8-9cde-b4afab8e9658.PNG)

![material_dimmablecolorlight_hue-iris](https://user-images.githubusercontent.com/35173972/43037531-4c2e2044-8d0e-11e8-98cc-8550a8ab8cee.PNG)

**Hue White Ambiance**

Teils ähnlich wie bei der RGB-Leuchte, also 0/1-Werte als Level+Zahl.

Verhalten im Material UI eigentlich auch wie bei der RGB-Leuchte, Dimmwert steht diesmal aber dauerhaft auf 1250%. Farbtemperatur funktioniert.

![iobroker_dimmablecolortemperaturelight_hue-gu9-white-ambiance](https://user-images.githubusercontent.com/35173972/43037606-39ce68f4-8d0f-11e8-967f-3361c3dbf81e.PNG)

![material_dimmablecolortemperaturelight_hue-gu9-white-ambiance](https://user-images.githubusercontent.com/35173972/43037609-3fe19f18-8d0f-11e8-9f0f-adf3ce867201.PNG)

**Comment by Apollon77** [comment]
Hi,

ich habe bei weitem nicht alle devices und von daher ist so ein Issue super!

Fragen:

>OnOff und IdentificationMode sind als Rolle Level und Art Zahl angelegt. Beim Z-Wave-Dimmer sind die 0/1-Werte dagegen alle als Art Logik + Rolle Switch angelegt. Scheint Material UI gar nicht zu schmecken.

und was ist jetzt besser und das Ziel? Switch besser?

> Im MaterialUI steht der Dimmwert die ganze Zeit auf 2500%, keine State scheint einen Einfluss darauf zu haben. Beim ändern via Slider springt der Wert immer zurück auf 50%. Dimmwert 0 wird an homee beim Ausschalten via button gesendet, der Zustand anschließend scheint aber eine Rückmeldung zu fehlen (drehender Kringel verschwindet nicht). Auch der Ein/Aus-Zustand wird nicht angezeigt.

Ok das klingt nach Material issue ... wird an Homee alles korrekt gesetzt und empfangen?
Das ist die Trennung. Homee adapter muss sinnvolle/korrekte Rollen haben. Dann muss der material adapter die korrekt anzeigen.

Also erstmal die Rollen in ioBroker glatt ziehen (Übersicht übrigens hier: https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md) und dann issues bei material wenn dort komische Dinge angezeigt werden

**Comment by Apollon77** [comment]
Die 0.3.0 hat einige Rollen angepasst, für mehr Bitte neue Issues anlegen
